apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.fullname" . }}-livekit-key
  labels: {{ include "acp.labels" . | nindent 4 }}
stringData:
  apiKey: "{{ .Values.livekit.apiKey }}"
  apiSecret: "{{ .Values.livekit.apiSecret }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.fullname" . }}-azure-key
  labels: {{ include "acp.labels" . | nindent 4 }}
stringData:
  apiKey: "{{ .Values.azure.openai.apiKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acp.fullname" . }}-deepgram-key
  labels: {{ include "acp.labels" . | nindent 4 }}
stringData:
  apiKey: "{{ .Values.deepgram.apiKey }}"