"""Email sender for ACP plan delivery using Azure Communication Services Email.

Configure your Azure Communication Services resource in .env:

    ACS_CONNECTION_STRING=endpoint=https://...;accesskey=...
    ACS_SENDER_DOMAIN=DoNotReply@xxxxx.azurecomm.net

To create an Azure Communication Services resource:
  1. Go to https://portal.azure.com → Create a resource → Communication Services
  2. Create the resource in Australia East for lowest latency
  3. Go to "Email" → "Domains" → "Add a free Azure-managed domain"
  4. Copy the connection string from "Primary Key" page
  5. Copy the sender domain from the "Domains" page (e.g. DoNotReply@xxxxx.azurecomm.net)
"""

import io
import logging
import os

import docx
from azure.communication.email import EmailClient
from docx.shared import Pt, RGBColor

logger = logging.getLogger("acp-agent.email")


def _get_env(key: str) -> str | None:
    return os.environ.get(key) or None


def generate_acp_docx(
    plan_summary: str,
    transcript: list[dict],
    preferences: dict,
) -> bytes:
    """Generate a formatted Word document containing the ACP plan details."""
    doc = docx.Document()

    # Define a custom title style
    title_style = doc.styles['Title']
    title_style.font.name = 'Arial'
    title_style.font.size = Pt(22)
    title_style.font.bold = True
    title_style.font.color.rgb = RGBColor(44, 95, 124)  # #2c5f7c

    doc.add_title("Advanced Care Planning Summary")
    doc.add_paragraph("This document was generated by an AI assistant during your Advanced Care Planning conversation.")

    # 1. Plan Overview
    if plan_summary:
        doc.add_heading("Plan Overview", level=1)
        doc.add_paragraph(plan_summary)

    # 2. Your Preferences
    doc.add_heading("Your Preferences", level=1)
    if preferences:
        for category, details in preferences.items():
            cat_name = category.replace("_", " ").title()
            doc.add_heading(cat_name, level=2)
            if isinstance(details, dict):
                for k, v in details.items():
                    key_name = k.replace("_", " ").title()
                    if isinstance(v, list):
                        val_str = ", ".join(str(x) for x in v) if v else "None recorded"
                    elif v is True:
                        val_str = "Yes"
                    elif v is False:
                        val_str = "No"
                    elif v is None:
                        val_str = "None recorded"
                    else:
                        val_str = str(v)

                    p = doc.add_paragraph()
                    p.add_run(f"{key_name}: ").bold = True
                    p.add_run(val_str)
            else:
                doc.add_paragraph(str(details))
    else:
        doc.add_paragraph("No preferences were recorded.")

    # 3. Conversation Transcript
    doc.add_heading("Conversation Transcript", level=1)
    if transcript:
        for entry in transcript:
            role_label = "You" if entry.get("role") == "user" else "Assistant"
            p = doc.add_paragraph()
            p.add_run(f"{role_label}: ").bold = True
            p.add_run(entry.get("text", ""))
    else:
        doc.add_paragraph("No transcript available.")

    # Disclaimer / Footer Section
    doc.add_page_break()
    doc.add_heading("Next Steps & Disclaimer", level=1)
    p_disclaimer = doc.add_paragraph()
    p_disclaimer.add_run("Next steps: ").bold = True
    p_disclaimer.add_run(
        "Share these wishes with your substitute decision-maker, family, and GP. "
        "Formalise your Advance Care Directive through your state or territory's health department.\n\n"
    )
    p_disclaimer.add_run("Disclaimer: ").bold = True
    p_disclaimer.add_run(
        "This summary was generated by an AI assistant and should be reviewed by you and your "
        "healthcare provider before being formalised. It is not a legal document."
    )

    # Save to memory buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()



def is_configured() -> bool:
    """Check if ACS Email credentials are configured."""
    return all([
        _get_env("ACS_CONNECTION_STRING"),
        _get_env("ACS_SENDER_DOMAIN"),
    ])


def generate_transcript_txt(transcript: list[dict]) -> bytes:
    """Generate a plain text transcript from the list of transcript entries."""
    lines = [
        "==================================================",
        "  Advanced Care Planning Conversation Transcript  ",
        "==================================================",
        ""
    ]
    if transcript:
        for entry in transcript:
            role = entry.get("role", "unknown")
            role_label = "User" if role == "user" else "Assistant"
            text = entry.get("text", "")
            lines.append(f"[{role_label}]: {text}")
            lines.append("")
    else:
        lines.append("No transcript available.")
    return "\n".join(lines).encode("utf-8")


def send_plan_email(
    to_email: str,
    plan_summary: str,
    transcript: list[dict],
    preferences: dict,
    audio_path: str | None = None,
) -> bool:
    """
    Send an ACP plan email via Azure Communication Services.

    Args:
        to_email: Recipient email address.
        plan_summary: Generated ACP plan summary text.
        transcript: Full conversation transcript as list of {role, text} dicts.
        preferences: Extracted preferences dict.
        audio_path: Unused (audio is no longer attached for privacy/size).

    Returns:
        True if sent successfully, False otherwise.
    """
    conn_str = _get_env("ACS_CONNECTION_STRING")
    sender = _get_env("ACS_SENDER_DOMAIN")

    if not conn_str or not sender:
        logger.error(
            "Azure Communication Services not configured. "
            "Set ACS_CONNECTION_STRING and ACS_SENDER_DOMAIN in .env"
        )
        return False

    attachments = []

    # 1. Generate and attach the Word document (.docx report)
    try:
        import base64
        docx_bytes = generate_acp_docx(plan_summary, transcript, preferences)
        attachments.append({
            "name": "Advanced_Care_Plan.docx",
            "contentType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "contentInBase64": base64.b64encode(docx_bytes).decode(),
        })
    except Exception as e:
        logger.error("Failed to generate/attach Word document: %s", e)

    # 2. Generate and attach the raw transcript text file
    try:
        import base64
        txt_bytes = generate_transcript_txt(transcript)
        attachments.append({
            "name": "Conversation_Transcript.txt",
            "contentType": "text/plain",
            "contentInBase64": base64.b64encode(txt_bytes).decode(),
        })
    except Exception as e:
        logger.error("Failed to generate/attach transcript text file: %s", e)

    # Build the HTML body
    html_parts = ["""
        <html><body style="font-family: Arial, sans-serif; max-width: 640px; margin: auto;">
        <h2 style="color: #2c5f7c;">Your Advanced Care Planning Summary</h2>
    """]

    if plan_summary:
        html_parts.append(
            f"<h3 style='color: #333;'>Plan Overview</h3>"
            f"<p style='line-height: 1.6;'>{plan_summary}</p>"
        )

    html_parts.append("<h3 style='color: #333;'>Your Preferences</h3>")
    if preferences:
        html_parts.append("<table style='width:100%;border-collapse:collapse;'>")
        for key, val in preferences.items():
            html_parts.append(
                f"<tr style='border-bottom:1px solid #eee;'>"
                f"<td style='padding:8px;font-weight:bold;width:40%;'>{key}</td>"
                f"<td style='padding:8px;'>{val}</td></tr>"
            )
        html_parts.append("</table>")
    else:
        html_parts.append("<p style='color:#666;'>No preferences were recorded.</p>")

    # Transcript preview (scrollable box)
    html_parts.append("<h3 style='color: #333;'>Conversation Transcript Preview</h3>")
    if transcript:
        html_parts.append("<div style='background:#f5f5f5;padding:12px;border-radius:8px;max-height:300px;overflow-y:auto;'>")
        for entry in transcript:
            role_label = "You" if entry["role"] == "user" else "Assistant"
            html_parts.append(
                f"<p style='margin: 6px 0;'><strong>{role_label}:</strong> {entry['text']}</p>"
            )
        html_parts.append("</div>")
        html_parts.append("<p style='font-size:0.85em;color:#666;'>Note: The full transcript is attached as a text file.</p>")
    else:
        html_parts.append("<p style='color:#666;'>No transcript available.</p>")

    # Next steps
    html_parts.append("""
        <hr style='border:none;border-top:1px solid #ddd;margin:24px 0;'>
        <p style="color:#555;font-size:0.9em;">
            <strong>Next steps:</strong> Share these wishes with your
            substitute decision-maker, family, and GP.
            Formalise your Advance Care Directive through your
            state or territory's health department.
        </p>
        <p style="color:#888;font-size:0.85em;">
            This summary was generated by an AI assistant and should be
            reviewed by you and your healthcare provider before being
            formalised. It is not a legal document.
        </p>
        </body></html>
    """)

    html_content = "\n".join(html_parts)

    # Build the email
    email_message = {
        "senderAddress": sender,
        "recipients": {
            "to": [{"address": to_email}],
        },
        "content": {
            "subject": "Your Advanced Care Planning Summary",
            "html": html_content,
        },
    }

    if attachments:
        email_message["attachments"] = attachments

    # Send
    try:
        client = EmailClient.from_connection_string(conn_str)
        poller = client.begin_send(email_message)
        result = poller.result()
        logger.info(
            "Sent ACP plan report and transcript to %s (message ID: %s)",
            to_email, result.message_id,
        )
        return True
    except Exception as e:
        logger.error("Failed to send email via ACS to %s: %s", to_email, e)
        return False
