"""Email sender for ACP plan delivery using Azure Communication Services Email.

Configure your Azure Communication Services resource in .env:

    ACS_CONNECTION_STRING=endpoint=https://...;accesskey=...
    ACS_SENDER_DOMAIN=DoNotReply@xxxxx.azurecomm.net

To create an Azure Communication Services resource:
  1. Go to https://portal.azure.com → Create a resource → Communication Services
  2. Create the resource in Australia East for lowest latency
  3. Go to "Email" → "Domains" → "Add a free Azure-managed domain"
  4. Copy the connection string from "Primary Key" page
  5. Copy the sender domain from the "Domains" page (e.g. DoNotReply@xxxxx.azurecomm.net)
"""

import logging
import os

from azure.communication.email import EmailClient

logger = logging.getLogger("acp-agent.email")


def _get_env(key: str) -> str | None:
    return os.environ.get(key) or None


def is_configured() -> bool:
    """Check if ACS Email credentials are configured."""
    return all([
        _get_env("ACS_CONNECTION_STRING"),
        _get_env("ACS_SENDER_DOMAIN"),
    ])


def send_plan_email(
    to_email: str,
    plan_summary: str,
    transcript: list[dict],
    preferences: dict,
    audio_path: str | None = None,
) -> bool:
    """
    Send an ACP plan email via Azure Communication Services.

    Args:
        to_email: Recipient email address.
        plan_summary: Generated ACP plan summary text.
        transcript: Full conversation transcript as list of {role, text} dicts.
        preferences: Extracted preferences dict.
        audio_path: Path to the WAV recording file, if any.

    Returns:
        True if sent successfully, False otherwise.
    """
    conn_str = _get_env("ACS_CONNECTION_STRING")
    sender = _get_env("ACS_SENDER_DOMAIN")

    if not conn_str or not sender:
        logger.error(
            "Azure Communication Services not configured. "
            "Set ACS_CONNECTION_STRING and ACS_SENDER_DOMAIN in .env"
        )
        return False

    # Build the HTML body
    html_parts = ["""
        <html><body style="font-family: Arial, sans-serif; max-width: 640px; margin: auto;">
        <h2 style="color: #2c5f7c;">Your Advanced Care Planning Summary</h2>
    """]

    if plan_summary:
        html_parts.append(
            f"<h3 style='color: #333;'>Plan Overview</h3>"
            f"<p style='line-height: 1.6;'>{plan_summary}</p>"
        )

    html_parts.append("<h3 style='color: #333;'>Your Preferences</h3>")
    if preferences:
        html_parts.append("<table style='width:100%;border-collapse:collapse;'>")
        for key, val in preferences.items():
            html_parts.append(
                f"<tr style='border-bottom:1px solid #eee;'>"
                f"<td style='padding:8px;font-weight:bold;width:40%;'>{key}</td>"
                f"<td style='padding:8px;'>{val}</td></tr>"
            )
        html_parts.append("</table>")
    else:
        html_parts.append("<p style='color:#666;'>No preferences were recorded.</p>")

    # Transcript
    html_parts.append("<h3 style='color: #333;'>Conversation Transcript</h3>")
    if transcript:
        html_parts.append("<div style='background:#f5f5f5;padding:12px;border-radius:8px;'>")
        for entry in transcript:
            role_label = "You" if entry["role"] == "user" else "Assistant"
            html_parts.append(
                f"<p><strong>{role_label}:</strong> {entry['text']}</p>"
            )
        html_parts.append("</div>")
    else:
        html_parts.append("<p style='color:#666;'>No transcript available.</p>")

    # Next steps
    html_parts.append("""
        <hr style='border:none;border-top:1px solid #ddd;margin:24px 0;'>
        <p style="color:#555;font-size:0.9em;">
            <strong>Next steps:</strong> Share these wishes with your
            substitute decision-maker, family, and GP.
            Formalise your Advance Care Directive through your
            state or territory's health department.
        </p>
        <p style="color:#888;font-size:0.85em;">
            This summary was generated by an AI assistant and should be
            reviewed by you and your healthcare provider before being
            formalised. It is not a legal document.
        </p>
        </body></html>
    """)

    html_content = "\n".join(html_parts)

    # Build the email
    email_message = {
        "senderAddress": sender,
        "recipients": {
            "to": [{"address": to_email}],
        },
        "content": {
            "subject": "Your Advanced Care Planning Summary",
            "html": html_content,
        },
    }

    # Attach audio if available
    if audio_path and os.path.exists(audio_path):
        import base64
        try:
            with open(audio_path, "rb") as af:
                audio_bytes = af.read()
            email_message["attachments"] = [
                {
                    "name": os.path.basename(audio_path),
                    "contentType": "audio/wav",
                    "contentInBase64": base64.b64encode(audio_bytes).decode(),
                }
            ]
        except Exception as e:
            logger.warning("Failed to attach audio %s: %s", audio_path, e)

    # Send
    try:
        client = EmailClient.from_connection_string(conn_str)
        poller = client.begin_send(email_message)
        result = poller.result()
        logger.info(
            "Sent ACP plan to %s (message ID: %s, audio: %s)",
            to_email, result.message_id, "yes" if audio_path else "no",
        )
        return True
    except Exception as e:
        logger.error("Failed to send email via ACS to %s: %s", to_email, e)
        return False
